apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: natanaelm/general-service:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8010
      imagePullSecrets: 
      - name: general
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 8010
    targetPort: 8010
    nodePort: 30000
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysecret2
# type: natanaelm/general-service:latest
# data:
#     .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJuYXRhbmFlbG0iLCJwYXNzd29yZCI6IldoaXNwZXI0NiIsImVtYWlsIjoibmF0YW5hZWxtdXJzaWQwMDFAZ21haWwuY29tIiwiYXV0aCI6ImJtRjBZVzVoWld4dE9sZG9hWE53WlhJME5nPT0ifX19

