version: "3"

services:
  user:
    build: ./user-service
    container_name: user-service
    ports:
      - 3000:3000
    depends_on:
      - redis

  general:
    build: ./general-service
    container_name: general-service
    ports:
      - 8010:8010

  sales:
    build: ./sales-service
    container_name: sales-service
    ports:
      - 8020:8020

  finance:
    build: ./finance-service
    container_name: finance-service
    ports:
      - 8030:8030

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672

  kong:
    container_name: kong
    build:
      context: ./apigateway-service
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_LOG_LEVEL=debug
      - KONG_PLUGINS=bundled
    ports:
    - "8000:8000/tcp"
    - "127.0.0.1:8001:8001/tcp"
    - "8443:8443/tcp"
    - "127.0.0.1:8444:8444/tcp"